# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import authorize_pb2 as authorize__pb2


class authorizeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.authorizeClient = channel.unary_unary(
                '/authorize.authorizeService/authorizeClient',
                request_serializer=authorize__pb2.AuthorizeRequest.SerializeToString,
                response_deserializer=authorize__pb2.AuthorizeResponse.FromString,
                )


class authorizeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def authorizeClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_authorizeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'authorizeClient': grpc.unary_unary_rpc_method_handler(
                    servicer.authorizeClient,
                    request_deserializer=authorize__pb2.AuthorizeRequest.FromString,
                    response_serializer=authorize__pb2.AuthorizeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'authorize.authorizeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class authorizeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def authorizeClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/authorize.authorizeService/authorizeClient',
            authorize__pb2.AuthorizeRequest.SerializeToString,
            authorize__pb2.AuthorizeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
