# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serverAvailability.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='serverAvailability.proto',
  package='serverAvailablility',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18serverAvailability.proto\x12\x13serverAvailablility\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa3\x01\n\x07Message\x12\x10\n\x08response\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12:\n\x08\x61vailReq\x18\x03 \x01(\x0b\x32(.serverAvailablility.AvailabilityRequest\x12;\n\x08\x61vailRes\x18\x04 \x01(\x0b\x32).serverAvailablility.AvailabilityResponse\"e\n\x13\x41vailabilityRequest\x12.\n\nclientTime\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04test\x18\x03 \x01(\t\x12\x10\n\x08hostname\x18\x02 \x01(\t\"4\n\x14\x41vailabilityResponse\x12\n\n\x02up\x18\x01 \x01(\x08\x12\x10\n\x08serverid\x18\x02 \x01(\x05\x32z\n\x0bserverAvail\x12k\n\x12serverAvailability\x12(.serverAvailablility.AvailabilityRequest\x1a).serverAvailablility.AvailabilityResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='serverAvailablility.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='serverAvailablility.Message.response', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='serverAvailablility.Message.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='availReq', full_name='serverAvailablility.Message.availReq', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='availRes', full_name='serverAvailablility.Message.availRes', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=246,
)


_AVAILABILITYREQUEST = _descriptor.Descriptor(
  name='AvailabilityRequest',
  full_name='serverAvailablility.AvailabilityRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientTime', full_name='serverAvailablility.AvailabilityRequest.clientTime', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='test', full_name='serverAvailablility.AvailabilityRequest.test', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hostname', full_name='serverAvailablility.AvailabilityRequest.hostname', index=2,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=349,
)


_AVAILABILITYRESPONSE = _descriptor.Descriptor(
  name='AvailabilityResponse',
  full_name='serverAvailablility.AvailabilityResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='up', full_name='serverAvailablility.AvailabilityResponse.up', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='serverid', full_name='serverAvailablility.AvailabilityResponse.serverid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=403,
)

_MESSAGE.fields_by_name['availReq'].message_type = _AVAILABILITYREQUEST
_MESSAGE.fields_by_name['availRes'].message_type = _AVAILABILITYRESPONSE
_AVAILABILITYREQUEST.fields_by_name['clientTime'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['AvailabilityRequest'] = _AVAILABILITYREQUEST
DESCRIPTOR.message_types_by_name['AvailabilityResponse'] = _AVAILABILITYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'serverAvailability_pb2'
  # @@protoc_insertion_point(class_scope:serverAvailablility.Message)
  })
_sym_db.RegisterMessage(Message)

AvailabilityRequest = _reflection.GeneratedProtocolMessageType('AvailabilityRequest', (_message.Message,), {
  'DESCRIPTOR' : _AVAILABILITYREQUEST,
  '__module__' : 'serverAvailability_pb2'
  # @@protoc_insertion_point(class_scope:serverAvailablility.AvailabilityRequest)
  })
_sym_db.RegisterMessage(AvailabilityRequest)

AvailabilityResponse = _reflection.GeneratedProtocolMessageType('AvailabilityResponse', (_message.Message,), {
  'DESCRIPTOR' : _AVAILABILITYRESPONSE,
  '__module__' : 'serverAvailability_pb2'
  # @@protoc_insertion_point(class_scope:serverAvailablility.AvailabilityResponse)
  })
_sym_db.RegisterMessage(AvailabilityResponse)



_SERVERAVAIL = _descriptor.ServiceDescriptor(
  name='serverAvail',
  full_name='serverAvailablility.serverAvail',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=405,
  serialized_end=527,
  methods=[
  _descriptor.MethodDescriptor(
    name='serverAvailability',
    full_name='serverAvailablility.serverAvail.serverAvailability',
    index=0,
    containing_service=None,
    input_type=_AVAILABILITYREQUEST,
    output_type=_AVAILABILITYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVERAVAIL)

DESCRIPTOR.services_by_name['serverAvail'] = _SERVERAVAIL

# @@protoc_insertion_point(module_scope)
