# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serverTopology.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='serverTopology.proto',
  package='servertoplogy',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14serverTopology.proto\x12\rservertoplogy\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8d\x01\n\x07Message\x12\x10\n\x08response\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12/\n\x07topoReq\x18\x03 \x01(\x0b\x32\x1e.servertoplogy.topologyRequest\x12\x30\n\x07topoRes\x18\x04 \x01(\x0b\x32\x1f.servertoplogy.topologyResponse\"O\n\x0ftopologyRequest\x12\x14\n\x0ctargetserver\x18\x01 \x01(\t\x12\x12\n\ndevicetype\x18\x02 \x01(\t\x12\x12\n\ntagpattern\x18\x03 \x01(\t\"=\n\x10topologyResponse\x12)\n\x0ctopologyrows\x18\x01 \x03(\x0b\x32\x13.servertoplogy.Node\"O\n\x04Node\x12\x10\n\x08nodename\x18\x01 \x01(\t\x12\x12\n\ndevicetype\x18\x02 \x01(\t\x12\x10\n\x08\x64\x65viceid\x18\x03 \x01(\t\x12\x0f\n\x07tagname\x18\x04 \x01(\t2f\n\x0ftopologyService\x12S\n\x0eserverTopology\x12\x1e.servertoplogy.topologyRequest\x1a\x1f.servertoplogy.topologyResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='servertoplogy.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='servertoplogy.Message.response', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='servertoplogy.Message.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='topoReq', full_name='servertoplogy.Message.topoReq', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='topoRes', full_name='servertoplogy.Message.topoRes', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=214,
)


_TOPOLOGYREQUEST = _descriptor.Descriptor(
  name='topologyRequest',
  full_name='servertoplogy.topologyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='targetserver', full_name='servertoplogy.topologyRequest.targetserver', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='devicetype', full_name='servertoplogy.topologyRequest.devicetype', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tagpattern', full_name='servertoplogy.topologyRequest.tagpattern', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=295,
)


_TOPOLOGYRESPONSE = _descriptor.Descriptor(
  name='topologyResponse',
  full_name='servertoplogy.topologyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='topologyrows', full_name='servertoplogy.topologyResponse.topologyrows', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=358,
)


_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='servertoplogy.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodename', full_name='servertoplogy.Node.nodename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='devicetype', full_name='servertoplogy.Node.devicetype', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deviceid', full_name='servertoplogy.Node.deviceid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tagname', full_name='servertoplogy.Node.tagname', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=360,
  serialized_end=439,
)

_MESSAGE.fields_by_name['topoReq'].message_type = _TOPOLOGYREQUEST
_MESSAGE.fields_by_name['topoRes'].message_type = _TOPOLOGYRESPONSE
_TOPOLOGYRESPONSE.fields_by_name['topologyrows'].message_type = _NODE
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['topologyRequest'] = _TOPOLOGYREQUEST
DESCRIPTOR.message_types_by_name['topologyResponse'] = _TOPOLOGYRESPONSE
DESCRIPTOR.message_types_by_name['Node'] = _NODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'serverTopology_pb2'
  # @@protoc_insertion_point(class_scope:servertoplogy.Message)
  })
_sym_db.RegisterMessage(Message)

topologyRequest = _reflection.GeneratedProtocolMessageType('topologyRequest', (_message.Message,), {
  'DESCRIPTOR' : _TOPOLOGYREQUEST,
  '__module__' : 'serverTopology_pb2'
  # @@protoc_insertion_point(class_scope:servertoplogy.topologyRequest)
  })
_sym_db.RegisterMessage(topologyRequest)

topologyResponse = _reflection.GeneratedProtocolMessageType('topologyResponse', (_message.Message,), {
  'DESCRIPTOR' : _TOPOLOGYRESPONSE,
  '__module__' : 'serverTopology_pb2'
  # @@protoc_insertion_point(class_scope:servertoplogy.topologyResponse)
  })
_sym_db.RegisterMessage(topologyResponse)

Node = _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), {
  'DESCRIPTOR' : _NODE,
  '__module__' : 'serverTopology_pb2'
  # @@protoc_insertion_point(class_scope:servertoplogy.Node)
  })
_sym_db.RegisterMessage(Node)



_TOPOLOGYSERVICE = _descriptor.ServiceDescriptor(
  name='topologyService',
  full_name='servertoplogy.topologyService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=441,
  serialized_end=543,
  methods=[
  _descriptor.MethodDescriptor(
    name='serverTopology',
    full_name='servertoplogy.topologyService.serverTopology',
    index=0,
    containing_service=None,
    input_type=_TOPOLOGYREQUEST,
    output_type=_TOPOLOGYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TOPOLOGYSERVICE)

DESCRIPTOR.services_by_name['topologyService'] = _TOPOLOGYSERVICE

# @@protoc_insertion_point(module_scope)
