# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smuTags.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='smuTags.proto',
  package='smuTags',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rsmuTags.proto\x12\x07smuTags\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x85\x01\n\x07Message\x12\x10\n\x08response\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12+\n\nsmuTagsReq\x18\x03 \x01(\x0b\x32\x17.smuTags.smuTagsRequest\x12,\n\nsmuTagsRes\x18\x04 \x01(\x0b\x32\x18.smuTags.smuTagsResponse\"G\n\x0esmuTagsRequest\x12\x10\n\x08hostname\x18\x01 \x01(\t\x12\x12\n\ndevicetype\x18\x02 \x01(\t\x12\x0f\n\x07taglist\x18\x03 \x01(\t\"5\n\x0fsmuTagsResponse\x12\"\n\x06result\x18\x01 \x03(\x0b\x32\x12.smuTags.returnTag\"\\\n\treturnTag\x12\x0f\n\x07tagname\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x10\n\x08\x64\x61tetime\x18\x03 \x01(\t\x12\r\n\x05ticks\x18\x04 \x01(\x03\x12\x0e\n\x06status\x18\x05 \x01(\t2U\n\x0fsmuTags_Service\x12\x42\n\x0bsmuTags_rpc\x12\x17.smuTags.smuTagsRequest\x1a\x18.smuTags.smuTagsResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,])




_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='smuTags.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='smuTags.Message.response', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='smuTags.Message.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='smuTagsReq', full_name='smuTags.Message.smuTagsReq', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='smuTagsRes', full_name='smuTags.Message.smuTagsRes', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=225,
)


_SMUTAGSREQUEST = _descriptor.Descriptor(
  name='smuTagsRequest',
  full_name='smuTags.smuTagsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hostname', full_name='smuTags.smuTagsRequest.hostname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='devicetype', full_name='smuTags.smuTagsRequest.devicetype', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='taglist', full_name='smuTags.smuTagsRequest.taglist', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=298,
)


_SMUTAGSRESPONSE = _descriptor.Descriptor(
  name='smuTagsResponse',
  full_name='smuTags.smuTagsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='smuTags.smuTagsResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=300,
  serialized_end=353,
)


_RETURNTAG = _descriptor.Descriptor(
  name='returnTag',
  full_name='smuTags.returnTag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tagname', full_name='smuTags.returnTag.tagname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='smuTags.returnTag.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='datetime', full_name='smuTags.returnTag.datetime', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ticks', full_name='smuTags.returnTag.ticks', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='smuTags.returnTag.status', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=355,
  serialized_end=447,
)

_MESSAGE.fields_by_name['smuTagsReq'].message_type = _SMUTAGSREQUEST
_MESSAGE.fields_by_name['smuTagsRes'].message_type = _SMUTAGSRESPONSE
_SMUTAGSRESPONSE.fields_by_name['result'].message_type = _RETURNTAG
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['smuTagsRequest'] = _SMUTAGSREQUEST
DESCRIPTOR.message_types_by_name['smuTagsResponse'] = _SMUTAGSRESPONSE
DESCRIPTOR.message_types_by_name['returnTag'] = _RETURNTAG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'smuTags_pb2'
  # @@protoc_insertion_point(class_scope:smuTags.Message)
  })
_sym_db.RegisterMessage(Message)

smuTagsRequest = _reflection.GeneratedProtocolMessageType('smuTagsRequest', (_message.Message,), {
  'DESCRIPTOR' : _SMUTAGSREQUEST,
  '__module__' : 'smuTags_pb2'
  # @@protoc_insertion_point(class_scope:smuTags.smuTagsRequest)
  })
_sym_db.RegisterMessage(smuTagsRequest)

smuTagsResponse = _reflection.GeneratedProtocolMessageType('smuTagsResponse', (_message.Message,), {
  'DESCRIPTOR' : _SMUTAGSRESPONSE,
  '__module__' : 'smuTags_pb2'
  # @@protoc_insertion_point(class_scope:smuTags.smuTagsResponse)
  })
_sym_db.RegisterMessage(smuTagsResponse)

returnTag = _reflection.GeneratedProtocolMessageType('returnTag', (_message.Message,), {
  'DESCRIPTOR' : _RETURNTAG,
  '__module__' : 'smuTags_pb2'
  # @@protoc_insertion_point(class_scope:smuTags.returnTag)
  })
_sym_db.RegisterMessage(returnTag)



_SMUTAGS_SERVICE = _descriptor.ServiceDescriptor(
  name='smuTags_Service',
  full_name='smuTags.smuTags_Service',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=449,
  serialized_end=534,
  methods=[
  _descriptor.MethodDescriptor(
    name='smuTags_rpc',
    full_name='smuTags.smuTags_Service.smuTags_rpc',
    index=0,
    containing_service=None,
    input_type=_SMUTAGSREQUEST,
    output_type=_SMUTAGSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SMUTAGS_SERVICE)

DESCRIPTOR.services_by_name['smuTags_Service'] = _SMUTAGS_SERVICE

# @@protoc_insertion_point(module_scope)
