# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smuTags_path_all.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='smuTags_path_all.proto',
  package='smuTags_path_all',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16smuTags_path_all.proto\x12\x10smuTags_path_all\"\x97\x01\n\x07Message\x12\x10\n\x08response\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x34\n\nsmuTagsReq\x18\x03 \x01(\x0b\x32 .smuTags_path_all.smuTagsRequest\x12\x35\n\nsmuTagsRes\x18\x04 \x01(\x0b\x32!.smuTags_path_all.smuTagsResponse\"D\n\x0esmuTagsRequest\x12\x12\n\ntagpattern\x18\x01 \x01(\t\x12\x0f\n\x07groupby\x18\x02 \x01(\t\x12\r\n\x05paths\x18\x03 \x03(\t\"C\n\x0fsmuTagsResponse\x12\x30\n\x0bsmuTags_all\x18\x01 \x03(\x0b\x32\x1b.smuTags_path_all.returnTag\"M\n\treturnTag\x12\x0f\n\x07tagname\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x10\n\x08\x64\x61tetime\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t2q\n\x14smuTags_path_Service\x12Y\n\x10smuTags_path_rpc\x12 .smuTags_path_all.smuTagsRequest\x1a!.smuTags_path_all.smuTagsResponse\"\x00\x62\x06proto3'
)




_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='smuTags_path_all.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='smuTags_path_all.Message.response', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='smuTags_path_all.Message.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='smuTagsReq', full_name='smuTags_path_all.Message.smuTagsReq', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='smuTagsRes', full_name='smuTags_path_all.Message.smuTagsRes', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=196,
)


_SMUTAGSREQUEST = _descriptor.Descriptor(
  name='smuTagsRequest',
  full_name='smuTags_path_all.smuTagsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tagpattern', full_name='smuTags_path_all.smuTagsRequest.tagpattern', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='groupby', full_name='smuTags_path_all.smuTagsRequest.groupby', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='paths', full_name='smuTags_path_all.smuTagsRequest.paths', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=266,
)


_SMUTAGSRESPONSE = _descriptor.Descriptor(
  name='smuTagsResponse',
  full_name='smuTags_path_all.smuTagsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='smuTags_all', full_name='smuTags_path_all.smuTagsResponse.smuTags_all', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=335,
)


_RETURNTAG = _descriptor.Descriptor(
  name='returnTag',
  full_name='smuTags_path_all.returnTag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tagname', full_name='smuTags_path_all.returnTag.tagname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='smuTags_path_all.returnTag.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='datetime', full_name='smuTags_path_all.returnTag.datetime', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='smuTags_path_all.returnTag.status', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=337,
  serialized_end=414,
)

_MESSAGE.fields_by_name['smuTagsReq'].message_type = _SMUTAGSREQUEST
_MESSAGE.fields_by_name['smuTagsRes'].message_type = _SMUTAGSRESPONSE
_SMUTAGSRESPONSE.fields_by_name['smuTags_all'].message_type = _RETURNTAG
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['smuTagsRequest'] = _SMUTAGSREQUEST
DESCRIPTOR.message_types_by_name['smuTagsResponse'] = _SMUTAGSRESPONSE
DESCRIPTOR.message_types_by_name['returnTag'] = _RETURNTAG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'smuTags_path_all_pb2'
  # @@protoc_insertion_point(class_scope:smuTags_path_all.Message)
  })
_sym_db.RegisterMessage(Message)

smuTagsRequest = _reflection.GeneratedProtocolMessageType('smuTagsRequest', (_message.Message,), {
  'DESCRIPTOR' : _SMUTAGSREQUEST,
  '__module__' : 'smuTags_path_all_pb2'
  # @@protoc_insertion_point(class_scope:smuTags_path_all.smuTagsRequest)
  })
_sym_db.RegisterMessage(smuTagsRequest)

smuTagsResponse = _reflection.GeneratedProtocolMessageType('smuTagsResponse', (_message.Message,), {
  'DESCRIPTOR' : _SMUTAGSRESPONSE,
  '__module__' : 'smuTags_path_all_pb2'
  # @@protoc_insertion_point(class_scope:smuTags_path_all.smuTagsResponse)
  })
_sym_db.RegisterMessage(smuTagsResponse)

returnTag = _reflection.GeneratedProtocolMessageType('returnTag', (_message.Message,), {
  'DESCRIPTOR' : _RETURNTAG,
  '__module__' : 'smuTags_path_all_pb2'
  # @@protoc_insertion_point(class_scope:smuTags_path_all.returnTag)
  })
_sym_db.RegisterMessage(returnTag)



_SMUTAGS_PATH_SERVICE = _descriptor.ServiceDescriptor(
  name='smuTags_path_Service',
  full_name='smuTags_path_all.smuTags_path_Service',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=416,
  serialized_end=529,
  methods=[
  _descriptor.MethodDescriptor(
    name='smuTags_path_rpc',
    full_name='smuTags_path_all.smuTags_path_Service.smuTags_path_rpc',
    index=0,
    containing_service=None,
    input_type=_SMUTAGSREQUEST,
    output_type=_SMUTAGSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SMUTAGS_PATH_SERVICE)

DESCRIPTOR.services_by_name['smuTags_path_Service'] = _SMUTAGS_PATH_SERVICE

# @@protoc_insertion_point(module_scope)
