# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tagsList.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tagsList.proto',
  package='tagsList',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0etagsList.proto\x12\x08tagsList\x1a\x1fgoogle/protobuf/timestamp.proto\"\x93\x01\n\x07Message\x12\x10\n\x08response\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x32\n\rcreateTagsReq\x18\x03 \x01(\x0b\x32\x1b.tagsList.createTagsRequest\x12\x33\n\rcreateTagsRes\x18\x04 \x01(\x0b\x32\x1c.tagsList.createTagsResponse\"9\n\x11\x63reateTagsRequest\x12$\n\ttagsnames\x18\x01 \x03(\x0b\x32\x11.tagsList.Tagname\"\x1a\n\x07Tagname\x12\x0f\n\x07tagName\x18\x01 \x01(\t\"6\n\x12\x63reateTagsResponse\x12 \n\x08tagslist\x18\x01 \x03(\x0b\x32\x0e.tagsList.Node\"L\n\x04Node\x12\x0f\n\x07tagname\x18\x01 \x01(\t\x12\r\n\x05tagid\x18\x02 \x01(\t\x12\x14\n\x0ctagtimestamp\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t2`\n\x0ftagsListservice\x12M\n\x0e\x63reateTagslist\x12\x1b.tagsList.createTagsRequest\x1a\x1c.tagsList.createTagsResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='tagsList.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='tagsList.Message.response', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='tagsList.Message.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='createTagsReq', full_name='tagsList.Message.createTagsReq', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='createTagsRes', full_name='tagsList.Message.createTagsRes', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=209,
)


_CREATETAGSREQUEST = _descriptor.Descriptor(
  name='createTagsRequest',
  full_name='tagsList.createTagsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tagsnames', full_name='tagsList.createTagsRequest.tagsnames', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=268,
)


_TAGNAME = _descriptor.Descriptor(
  name='Tagname',
  full_name='tagsList.Tagname',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tagName', full_name='tagsList.Tagname.tagName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=296,
)


_CREATETAGSRESPONSE = _descriptor.Descriptor(
  name='createTagsResponse',
  full_name='tagsList.createTagsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tagslist', full_name='tagsList.createTagsResponse.tagslist', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=298,
  serialized_end=352,
)


_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='tagsList.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tagname', full_name='tagsList.Node.tagname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tagid', full_name='tagsList.Node.tagid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tagtimestamp', full_name='tagsList.Node.tagtimestamp', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='tagsList.Node.status', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=354,
  serialized_end=430,
)

_MESSAGE.fields_by_name['createTagsReq'].message_type = _CREATETAGSREQUEST
_MESSAGE.fields_by_name['createTagsRes'].message_type = _CREATETAGSRESPONSE
_CREATETAGSREQUEST.fields_by_name['tagsnames'].message_type = _TAGNAME
_CREATETAGSRESPONSE.fields_by_name['tagslist'].message_type = _NODE
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['createTagsRequest'] = _CREATETAGSREQUEST
DESCRIPTOR.message_types_by_name['Tagname'] = _TAGNAME
DESCRIPTOR.message_types_by_name['createTagsResponse'] = _CREATETAGSRESPONSE
DESCRIPTOR.message_types_by_name['Node'] = _NODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'tagsList_pb2'
  # @@protoc_insertion_point(class_scope:tagsList.Message)
  })
_sym_db.RegisterMessage(Message)

createTagsRequest = _reflection.GeneratedProtocolMessageType('createTagsRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATETAGSREQUEST,
  '__module__' : 'tagsList_pb2'
  # @@protoc_insertion_point(class_scope:tagsList.createTagsRequest)
  })
_sym_db.RegisterMessage(createTagsRequest)

Tagname = _reflection.GeneratedProtocolMessageType('Tagname', (_message.Message,), {
  'DESCRIPTOR' : _TAGNAME,
  '__module__' : 'tagsList_pb2'
  # @@protoc_insertion_point(class_scope:tagsList.Tagname)
  })
_sym_db.RegisterMessage(Tagname)

createTagsResponse = _reflection.GeneratedProtocolMessageType('createTagsResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATETAGSRESPONSE,
  '__module__' : 'tagsList_pb2'
  # @@protoc_insertion_point(class_scope:tagsList.createTagsResponse)
  })
_sym_db.RegisterMessage(createTagsResponse)

Node = _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), {
  'DESCRIPTOR' : _NODE,
  '__module__' : 'tagsList_pb2'
  # @@protoc_insertion_point(class_scope:tagsList.Node)
  })
_sym_db.RegisterMessage(Node)



_TAGSLISTSERVICE = _descriptor.ServiceDescriptor(
  name='tagsListservice',
  full_name='tagsList.tagsListservice',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=432,
  serialized_end=528,
  methods=[
  _descriptor.MethodDescriptor(
    name='createTagslist',
    full_name='tagsList.tagsListservice.createTagslist',
    index=0,
    containing_service=None,
    input_type=_CREATETAGSREQUEST,
    output_type=_CREATETAGSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TAGSLISTSERVICE)

DESCRIPTOR.services_by_name['tagsListservice'] = _TAGSLISTSERVICE

# @@protoc_insertion_point(module_scope)
